run:
  timeout: 10m

output:
  sort-results: true

# https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

# https://golangci-lint.run/usage/configuration/#config-file
linters-settings:
  errorlint:
    asserts: false
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  nestif:
    min-complexity: 5
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
