name: 'Profile Updater'
description: 'This action updates your readme with Zenn, Qiita, etc.'
author: 'kumackey <kumak1t09e0@gmail.com>'
inputs:
  zenn_user_id:
    description: 'Zenn user id'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'list'
  color: 'gray-dark'