name: 'Profile Updater'
description: 'This action updates your readme with Zenn, connpass, Qiita, etc.'
author: 'kumackey <kumak1t09e0@gmail.com>'
inputs:
  zenn_user_id:
    description: 'Zenn user id'
    required: false
  zenn_max_articles:
    description: 'Zenn max article count, default 5'
    required: false
  connpass_nickname:
    description: 'connpass nickname'
    required: false
  connpass_max_events:
    description: 'connpass max event count, default 5'
    required: false
  qiita_user_id:
    description: 'Qiita user id'
    required: false
  qiita_max_articles:
    description: 'Qiita max article count, default 5'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'list'
  color: 'gray-dark'